#!/bin/bash -e

runpdflatex() {
	SOURCE=$1
	pdflatex -interaction=nonstopmode -synctex=-1 "$SOURCE.tex" > "$SOURCE.log" 2>&1
}
runflatex() {
	SOURCE=$1
	./flatex.exe "$SOURCE.tex" > "${SOURCE}_flatex.log" 2>&1
}
runall() {
	SOURCE=$1
	if [ -z "$SOURCE" ]; then
		echo "No source specified"
		exit 1
	fi
	runpdflatex $SOURCE
	runflatex $SOURCE
	echo "made $SOURCE"
}

ARGS_ALL=(
cv \
cv-long \
)
ARGS=()
if [ -z "$1" ] || [ "$1" = all ]; then
	ARGS=(${ARGS_ALL[@]})
else
	IFS="," read -a ARGS <<< "$1"
fi

for ARG in ${ARGS[@]}; do
	runall "$ARG"
done
